### ISSUE TITLE
Images are bigger on wider screen

### ISSUE THREAD

**Issue by mrepol742** [DumDevSA/dumdevsa.github.io#3]
## It appears the images and other content are bigger than it should be on desktop/wider screen than mobile phones.

![Screenshot](https://user-images.githubusercontent.com/62317165/167183146-7a3a231b-90a6-4789-8085-d1d59bc08af2.png)
![Screenshot](https://user-images.githubusercontent.com/62317165/167183263-b18defe5-5b66-4229-bca2-f17c69b05e5c.png)
![Screenshot](https://user-images.githubusercontent.com/62317165/167183299-6c3f8005-4949-42e1-a543-266edd97dd50.png)
## The site looks fine in mobile tho.
![Screenshot](https://user-images.githubusercontent.com/62317165/167183864-377ab8ce-ee7f-457b-85af-41760b3bf494.png)

**Comment by DumDevSA** [comment]
Hi Melvin and thanks for you review.  I acknowledge the inconvenience of
the site, however it is because of not having a PC. I'm therefore fixed in
mobile devices till I get a PC. Nevertheless, I will work on its
responsibility. Should you have any other suggestion, feel free to shoot.

S.M Dumisa

**Comment by mrepol742** [comment]
You can try and turning your phone into landscape that can somehow simulate desktop screens. You can use `media queries` to resize the images if the screen was wider than 1080p.

for example:
``` css
img {
    width: 450px;
}

@media (max-width:1080px) {
    img {
        width: 200px !important;
    }
}
```
or you can use to control the size while maintaining the proportion
``` css
img {
    height: auto; 
    width: auto; 
    max-width: 450px; 
    max-height: 450px;
}
```
